- import_tasks: requirements.yml
  become: True
  tags:
    - borg_install

- import_tasks: setup.yml
  become: True
  tags:
    - borg_setup

- import_tasks: restore.yml
  tags: borg_restore
  become: True
